'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property BeginnerNam1() As String
        Get
            Return CType(Me("BeginnerNam1"),String)
        End Get
        Set
            Me("BeginnerNam1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property BeginnerNam2() As String
        Get
            Return CType(Me("BeginnerNam2"),String)
        End Get
        Set
            Me("BeginnerNam2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property BeginnerNam3() As String
        Get
            Return CType(Me("BeginnerNam3"),String)
        End Get
        Set
            Me("BeginnerNam3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property IntermediateNam1() As String
        Get
            Return CType(Me("IntermediateNam1"),String)
        End Get
        Set
            Me("IntermediateNam1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property IntermediateNam2() As String
        Get
            Return CType(Me("IntermediateNam2"),String)
        End Get
        Set
            Me("IntermediateNam2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property IntermediateNam3() As String
        Get
            Return CType(Me("IntermediateNam3"),String)
        End Get
        Set
            Me("IntermediateNam3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property ExpertNam1() As String
        Get
            Return CType(Me("ExpertNam1"),String)
        End Get
        Set
            Me("ExpertNam1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property ExpertNam2() As String
        Get
            Return CType(Me("ExpertNam2"),String)
        End Get
        Set
            Me("ExpertNam2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Anonymous")>  _
    Public Property ExpertNam3() As String
        Get
            Return CType(Me("ExpertNam3"),String)
        End Get
        Set
            Me("ExpertNam3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property BeginnerSweeps1() As Integer
        Get
            Return CType(Me("BeginnerSweeps1"),Integer)
        End Get
        Set
            Me("BeginnerSweeps1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property BeginnerSweeps2() As Integer
        Get
            Return CType(Me("BeginnerSweeps2"),Integer)
        End Get
        Set
            Me("BeginnerSweeps2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property IntermediateSweeps1() As Integer
        Get
            Return CType(Me("IntermediateSweeps1"),Integer)
        End Get
        Set
            Me("IntermediateSweeps1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property IntermediateSweeps2() As Integer
        Get
            Return CType(Me("IntermediateSweeps2"),Integer)
        End Get
        Set
            Me("IntermediateSweeps2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property IntermediateSweeps3() As Integer
        Get
            Return CType(Me("IntermediateSweeps3"),Integer)
        End Get
        Set
            Me("IntermediateSweeps3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property ExpertSweeps1() As Integer
        Get
            Return CType(Me("ExpertSweeps1"),Integer)
        End Get
        Set
            Me("ExpertSweeps1") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property ExpertSweeps2() As Integer
        Get
            Return CType(Me("ExpertSweeps2"),Integer)
        End Get
        Set
            Me("ExpertSweeps2") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property ExpertSweeps3() As Integer
        Get
            Return CType(Me("ExpertSweeps3"),Integer)
        End Get
        Set
            Me("ExpertSweeps3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("999")>  _
    Public Property BeginnerSweeps3() As Integer
        Get
            Return CType(Me("BeginnerSweeps3"),Integer)
        End Get
        Set
            Me("BeginnerSweeps3") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property DefaultMode() As String
        Get
            Return CType(Me("DefaultMode"),String)
        End Get
        Set
            Me("DefaultMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property Sounds() As Boolean
        Get
            Return CType(Me("Sounds"),Boolean)
        End Get
        Set
            Me("Sounds") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Minesweeper_Flags.Settings
            Get
                Return Global.Minesweeper_Flags.Settings.Default
            End Get
        End Property
    End Module
End Namespace
